# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main
- feature/*
pool:
  vmImage: 'ubuntu-latest' 

variables:
   imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Build an image
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
     repository: $(imageName)
     command: build
     Dockerfile: app/Dockerfile
     

pr:
- main
- feature/*